version: "3"

services:
  server:
    build:
      context: ./server/
      dockerfile: ./.dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      MONGO_DATABASE: user
      MONGO_PORT: 27017
      ENV: production
    depends_on:
      - mongo

  mongo:
    image: "mongo:4.2.16-bionic"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: user
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./server/db/data/mongo/:/data/db
